# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License
version: "3"
services:
  app:
    build:
      context: .
      args:
        VERSION: ${VERSION}
    depends_on:
      - postgres
    environment:
      DB_USERNAME: user
      DATABASE: marketplace
      DB_PASSWORD: postgre
      DB_HOST: postgres
      DB_PORT: 5432
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    working_dir: /usr/src/app/openpaimarketplace/rest_server
    command: ["npm", "start"]

  postgres:
    image: postgres:12.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: marketplace
